### ISSUE TITLE
Sales Order print out

### ISSUE THREAD

**Issue by alikoyakp** [consoleerp/siyar_erpnext#3]
Sales order print out required as attached
![img_20170316_175414](https://cloud.githubusercontent.com/assets/23100999/24078998/f3e9ddd2-0c31-11e7-9d3e-72b2225da7cb.jpg)

**Comment by fahimalizain** [comment]
Invoice number in each line ??

**Comment by fahimalizain** [comment]
Sales Order or Sales Invoice ??

**Comment by fahimalizain** [comment]
Sales Invoice print out was made using the referenced picture. Close issue ?
