### ISSUE TITLE
Sales Order -- Customer Rate and Discount Rate Both required in the detail

### ISSUE THREAD

**Issue by alikoyakp** [consoleerp/siyar_erpnext#4]
Sales Order - Customer Rate and Discount Rate Both required in the detail

**Comment by fahimalizain** [comment]
Customer rate in Sales Invoice is entered as the normal rate in Sales Order.
On creation of Sales Invoice from Sales Order (using Sales Order->Make Invoice), the rate from Sales Order is taken as Sales Invoice Customer Rate-- customer discount % loaded and actual rate calculated.

We designed it so back then right ?
So, there is no concept of Customer Rate in Sales Order

**Comment by fahimalizain** [comment]
Closing issue as its leads to design change.
